definitions:
  req.Article:
    properties:
      category_id:
        description: 分类ID
        type: integer
      content:
        type: string
      cover_image:
        description: 文章封面
        type: string
      created_at:
        description: 发布时间
        type: integer
      status:
        description: 文章状态
        enum:
        - 0
        - 1
        type: integer
      tags:
        description: 标签
        items:
          type: string
        type: array
      title:
        type: string
      top:
        description: 是否置顶
        enum:
        - 0
        - 1
        type: integer
    required:
    - category_id
    - content
    - title
    type: object
  req.ArticleSertion:
    properties:
      key:
        description: 用于更新文章状态
        enum:
        - top
        - status
        type: string
      value:
        enum:
        - 0
        - 1
        type: integer
    type: object
  req.Cate:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - name
    type: object
  req.Comment:
    properties:
      article_id:
        type: integer
      content:
        type: string
      email:
        type: string
      parent_id:
        type: integer
      root_id:
        type: integer
      user_name:
        type: string
    required:
    - article_id
    - content
    - email
    - user_name
    type: object
  req.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - name
    type: object
  req.User:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  res.BasicInfo:
    properties:
      social:
        items:
          $ref: '#/definitions/site.Social'
        type: array
      user:
        $ref: '#/definitions/site.User'
    type: object
  res.ChildComment:
    properties:
      avatar:
        type: string
      content:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      parentId:
        description: 父评论ID 为空为二级评论 不为空为二级评论的回复
        type: integer
      userName:
        type: string
    type: object
  res.Comment:
    properties:
      avatar:
        type: string
      childComment:
        items:
          $ref: '#/definitions/res.ChildComment'
        type: array
      content:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      userName:
        type: string
    type: object
  res.OssConfig:
    properties:
      bucket:
        type: string
      domain:
        type: string
      imgprocess:
        type: string
      keyprefix:
        type: string
      region:
        type: string
      uptoken:
        type: string
    type: object
  res.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  res.SiteInfo:
    properties:
      articlecount:
        type: integer
      categorycount:
        type: integer
      record:
        type: string
      tagcount:
        type: integer
      viewscount:
        type: integer
    type: object
  site.Badge:
    properties:
      colorRight:
        type: string
      href:
        type: string
      logo:
        type: string
      nameLeft:
        type: string
      nameRight:
        type: string
    type: object
  site.Social:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  site.User:
    properties:
      avatar:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /article/get:
    get:
      consumes:
      - application/json
      description: 获取文章详情
      parameters:
      - description: 文章uuid
        in: query
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取文章详情
      tags:
      - 文章
  /article/list:
    get:
      consumes:
      - application/json
      description: 获取文章列表
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        minimum: 1
        name: page_num
        type: integer
      - in: query
        maximum: 20
        minimum: 1
        name: page_size
        type: integer
      - in: query
        name: title_like
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取文章列表
      tags:
      - 文章
  /article/manage/create:
    post:
      consumes:
      - application/json
      description: 创建文章
      parameters:
      - description: 文章信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.Article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 创建文章
      tags:
      - 文章
  /article/manage/delete/:uuid:
    delete:
      consumes:
      - multipart/form-data
      description: 删除文章
      parameters:
      - description: 文章uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 删除文章
      tags:
      - 文章
  /article/manage/list:
    get:
      consumes:
      - application/json
      description: 获取文章列表(管理员)
      parameters:
      - in: query
        name: cate_id
        type: integer
      - in: query
        minimum: 1
        name: page_num
        type: integer
      - in: query
        maximum: 20
        minimum: 1
        name: page_size
        type: integer
      - in: query
        name: title_like
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取文章列表(管理员)
      tags:
      - 文章
  /article/manage/update/:uuid:
    patch:
      consumes:
      - application/json
      parameters:
      - description: 文章uuid
        in: path
        name: uuid
        required: true
        type: string
      - description: 文章信息
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/req.ArticleSertion'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 局部更新文章
      tags:
      - 文章
    put:
      consumes:
      - application/json
      parameters:
      - description: 文章uuid
        in: path
        name: uuid
        required: true
        type: string
      - description: 文章信息
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/req.Article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 更新文章
      tags:
      - 文章
  /article/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: 搜索内容
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 搜索文章
      tags:
      - 文章
  /category/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取分类列表
      tags:
      - 分类
  /category/manage/create:
    post:
      parameters:
      - description: 创建分类
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.Cate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  type: integer
              type: object
      summary: 创建分类
      tags:
      - 分类
  /category/manage/delete/:id:
    delete:
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 删除分类
      tags:
      - 分类
  /category/manage/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取管理分类列表
      tags:
      - 分类
  /category/manage/update:
    put:
      parameters:
      - description: 更新分类
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.Cate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 更新分类
      tags:
      - 分类
  /comment/create:
    post:
      consumes:
      - application/json
      description: 创建评论
      parameters:
      - description: 评论
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  $ref: '#/definitions/res.Response'
              type: object
      summary: 创建评论
      tags:
      - 评论
  /comment/list/:uuid:
    get:
      consumes:
      - application/json
      description: 获取评论列表
      parameters:
      - description: 评论
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/res.Comment'
                  type: array
              type: object
      summary: 获取评论列表
      tags:
      - 评论
  /info/badges:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/site.Badge'
            type: array
      summary: 获取站点徽标信息
      tags:
      - 站点信息
  /info/basic:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.BasicInfo'
      summary: 获取站点基本信息
      tags:
      - 站点信息
  /info/site:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.SiteInfo'
      summary: 获取站点信息
      tags:
      - 站点信息
  /oss/uptoken:
    get:
      description: 获取oss上传token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.OssConfig'
      summary: OSS
      tags:
      - OSS
  /tag/hotlist/:size:
    get:
      description: 获取热门标签列表
      parameters:
      - description: 热门标签数量
        in: path
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取热门标签列表
      tags:
      - 标签
  /tag/list:
    get:
      consumes:
      - application/json
      description: 获取标签列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取标签列表
      tags:
      - 标签
  /tag/manage/create:
    post:
      description: 创建标签
      parameters:
      - description: 标签
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.Tag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 创建标签
      tags:
      - 标签
  /tag/manage/delete/:id:
    delete:
      parameters:
      - description: 标签ID
        in: formData
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 删除标签
      tags:
      - 标签
  /tag/manage/list:
    get:
      consumes:
      - application/json
      description: 获取标签管理列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取标签管理列表
      tags:
      - 标签
  /tag/manage/update:
    put:
      consumes:
      - application/json
      description: 更新标签
      parameters:
      - description: 标签
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/req.Tag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 更新标签
      tags:
      - 标签
  /user/login:
    post:
      parameters:
      - description: 用户名密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/req.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 登录
      tags:
      - 用户
  /user/manage/info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
      summary: 获取用户信息
      tags:
      - 用户
swagger: "2.0"
